### ISSUE TITLE
Plugin fails on pure command line environment

### ISSUE THREAD

**Issue by ykryshchuk** [ykryshchuk/umlet-maven-plugin#2]
When running the plugin on a linux server without X11 installed the plugin fails with an error like:

Caused by: org.apache.maven.plugin.PluginExecutionException: Execution validate-convert of goal com.kryshchuk.maven.plugins:umlet-maven-plugin:1.1.1-SNAPSHOT:convert failed: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.dnd.DropTarget.<init>(DropTarget.java:95)
        at java.awt.dnd.DropTarget.<init>(DropTarget.java:151)
        at com.baselet.gui.standalone.FileDrop.makeDropTarget(FileDrop.java:478)
        at com.baselet.gui.standalone.FileDrop.<init>(FileDrop.java:426)
        at com.baselet.gui.standalone.FileDrop.<init>(FileDrop.java:77)
        at com.baselet.diagram.DrawPanel.<init>(DrawPanel.java:62)
        at com.baselet.diagram.DiagramHandler.<init>(DiagramHandler.java:54)
        at com.baselet.diagram.DiagramHandler.<init>(DiagramHandler.java:47)
        at com.kryshchuk.maven.plugins.umlet.ConvertDiagramMojo$1.handleFile(ConvertDiagramMojo.java:70)
        at com.kryshchuk.maven.plugins.filevisitor.AbstractFileVisitor.visit(AbstractFileVisitor.java:21)
        at com.kryshchuk.maven.plugins.filevisitor.FileSetIterator.iterate(FileSetIterator.java:37)
        at com.kryshchuk.maven.plugins.filevisitor.FileSetIterator.iterate(FileSetIterator.java:34)
        at com.kryshchuk.maven.plugins.filevisitor.FileSetIterator.iterate(FileSetIterator.java:25)
        at com.kryshchuk.maven.plugins.umlet.ConvertDiagramMojo.processFileSet(ConvertDiagramMojo.java:112)
        at com.kryshchuk.maven.plugins.umlet.ConvertDiagramMojo.execute(ConvertDiagramMojo.java:98)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        ... 20 more

**Comment by rbi** [comment]
The problem occurs again in 1.2.0. It seams the fix for version 1.1.5 didn't make it into the new version.
