### ISSUE TITLE
umlet 13 support?

### ISSUE THREAD

**Issue by RainerW** [ykryshchuk/umlet-maven-plugin#5]
When running the maven Plugin with umlet 13 files I get the following error. When creating a diagram with Umlet 12.2 I don't get a error it creates a image.

So an update to 13.x would be nice. Any plans?

BTW: Have you thought about a "run" goal? Then my colleges would just need to execute a maven goal "umlet:run" instead of downloading umlet in the correct version.

TRACE : 
[INFO] Converting C:\workspaces\...\src\site\resources\uml\f01_system-architecture.uxf
[ERROR] Failed to convert diagram
java.io.IOException: Width (0) and height (0) cannot be <= 0
        at com.baselet.diagram.io.DiagramFileHandler.doExportAs(DiagramFileHandler.java:297)
        at com.kryshchuk.maven.plugins.umlet.ConvertDiagramMojo$1.handleFile(ConvertDiagramMojo.java:94)
        at com.kryshchuk.maven.plugins.filevisitor.AbstractFileVisitor.visit(AbstractFileVisitor.java:35)
        at com.kryshchuk.maven.plugins.filevisitor.FileSetIterator.iterate(FileSetIterator.java:59)
        at com.kryshchuk.maven.plugins.filevisitor.FileSetIterator.iterate(FileSetIterator.java:44)
        at com.kryshchuk.maven.plugins.umlet.ConvertDiagramMojo.processFileSet(ConvertDiagramMojo.java:135)
        at com.kryshchuk.maven.plugins.umlet.ConvertDiagramMojo.execute(ConvertDiagramMojo.java:118)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:364)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:198)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by ykryshchuk** [comment]
Hi Rainer, 

thank you for using the plugin. :)

I will evaluate your both requests in the next two weeks.

**Comment by ykryshchuk** [comment]
Hi Rainer,

could you please attach your sample uxf file? please also specify which maven and java version do you use.

I have created a diagram with umlet 13 standalone and it has been converted to an image. Well, the relations were missing on the image but I did not get the error.

Thanks

**Comment by RainerW** [comment]
I attached a maven project as zip (remove the .jpg)

The Project contains a version 13 file which will create the above error when using Maven 3.0.5. (  Maven Umlet Plugin is not compatible with a Maven 3.3)

![umlet-test zip](https://cloud.githubusercontent.com/assets/118649/8104385/a968c236-1030-11e5-967e-2bac9b6c2fa8.jpg)

**Comment by ykryshchuk** [comment]
released version 1.2, which should be available soon on maven central
